version: '3.8'

services:
  # Service pour la base de données MySQL
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lesmakiscodeu_the_end_page_db
      - MYSQL_USER=lesmakiscodeu
      - MYSQL_PASSWORD=LesM4ki!
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: 
